'use client'
import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { sb } from '../../lib/supabase'
import '../globals.css'

const NAV = [
  { id: 'overview', label: 'Overview' },
  { id: 'appointments', label: 'Appointments' },
  { id: 'clients', label: 'Clients' },
  { id: 'reviews', label: 'Reviews' },
  { id: 'campaigns', label: 'Automations' },
  { id: 'conversations', label: 'Conversations' },
  { id: 'services', label: 'Services' },
  { id: 'schedule', label: 'Schedule' },
  { id: 'ai', label: 'AI Advisor' },
  { id: 'notifications', label: 'Notifications' },
  { id: 'referrals', label: 'Referrals' },
  { id: 'settings', label: 'Settings' },
  ]

export default function Dashboard() {
    const router = useRouter()
    const [salon, setSalon] = useState(null)
    useEffect(() => {
          try {
                  const s = localStorage.getItem('sm_salon')
                  if (!s) { router.push('/login'); return }
                  setSalon(JSON.parse(s))
          } catch { router.push('/login') }
    }, [])

  const [tab, setTab] = useState('overview')
    const [data, setData] = useState({ services: [], appointments: [], reviews: [], clients: [], campaigns: [], ai_conversations: [] })
    const [loading, setLoading] = useState(true)
    const [aiQuery, setAiQuery] = useState('')
    const [aiResponse, setAiResponse] = useState('')
    const [aiLoading, setAiLoading] = useState(false)
    const [ghlKey, setGhlKey] = useState('')
    const [selectedClient, setSelectedClient] = useState(null)
    const [clientHistory, setClientHistory] = useState([])
    const [showCustomAutomation, setShowCustomAutomation] = useState(false)
    const [customAutomation, setCustomAutomation] = useState({ name: '', trigger: 'after_booking', message: '', delay_hours: 0 })
    const [notifLog, setNotifLog] = useState([])
    const [scheduleSettings, setScheduleSettings] = useState({ mon: { open: '08:00', close: '18:00', enabled: true }, tue: { open: '08:00', close: '18:00', enabled: true }, wed: { open: '08:00', close: '18:00', enabled: true }, thu: { open: '08:00', close: '18:00', enabled: true }, fri: { open: '08:00', close: '17:00', enabled: true }, sat: { open: '09:00', close: '15:00', enabled: false }, sun: { open: '09:00', close: '15:00', enabled: false }, slot_duration: 30, buffer_minutes: 0, blocked_dates: [] })
    const [blockDate, setBlockDate] = useState('')
    const [editingService, setEditingService] = useState(null)
    const [newService, setNewService] = useState({ name: '', category: 'Haircuts', duration: 45, price: 0, sort_order: 0 })
    const [conversations, setConversations] = useState([])
    const [selectedConvo, setSelectedConvo] = useState(null)
    const [convoReply, setConvoReply] = useState('')
    const [settingsForm, setSettingsForm] = useState({})

  useEffect(() => { if (salon?.id) load() }, [salon?.id])
    useEffect(() => { if (salon) setSettingsForm({ shop_name: salon.shop_name || '', owner_name: salon.owner_name || '', phone: salon.phone || '', email: salon.email || '', city: salon.city || '', state: salon.state || '', salon_type: salon.salon_type || '', passcode: salon.passcode || '' }) }, [salon])

  if (!salon) return <div style={{ minHeight: '100vh', background: '#080808' }} />

  const load = async () => {
        if (!salon?.id) return
        const [sv, ap, rv, cl, cp, ai] = await Promise.all([
                sb().from('salon_services').select('*').eq('salon_id', salon.id).order('sort_order'),
                sb().from('appointments').select('*').eq('salon_id', salon.id).order('created_at', { ascending: false }).limit(100),
                sb().from('salon_reviews').select('*').eq('salon_id', salon.id).order('created_at', { ascending: false }),
                sb().from('clients').select('*').eq('salon_id', salon.id).order('created_at', { ascending: false }).limit(100),
                sb().from('salon_campaigns').select('*').eq('salon_id', salon.id).order('campaign_type'),
                sb().from('ai_conversations').select('*').eq('salon_id', salon.id).order('created_at', { ascending: false }).limit(20),
              ])
        setData({ services: sv.data || [], appointments: ap.data || [], reviews: rv.data || [], clients: cl.data || [], campaigns: cp.data || [], ai_conversations: ai.data || [] })
        if (salon.schedule_settings) { try { setScheduleSettings(typeof salon.schedule_settings === 'string' ? JSON.parse(salon.schedule_settings) : salon.schedule_settings) } catch {} }
        const events = []
              ;(ap.data || []).slice(0, 5).forEach(a => events.push({ type: 'booking', text: `New booking: ${a.client_name} for ${a.service_name}`, time: a.created_at }))
        ;(rv.data || []).slice(0, 3).forEach(r => events.push({ type: 'review', text: `${r.author_name} left a ${r.stars}-star review`, time: r.created_at }))
        ;(cp.data || []).filter(c => c.is_active).forEach(c => events.push({ type: 'automation', text: `Automation active: ${c.name}`, time: c.updated_at || c.created_at }))
        events.sort((a, b) => new Date(b.time) - new Date(a.time))
        setNotifLog(events.slice(0, 20))
        setConversations((cl.data || []).filter(c => c.phone).map(c => ({ client: c, messages: [], lastMessage: c.last_visit_at ? `Last visit: ${new Date(c.last_visit_at).toLocaleDateString()}` : 'No messages yet' })))
        setLoading(false)
  }

  const deleteReview = async (id) => { if (!window.confirm('Remove this review?')) return; await sb().from('salon_reviews').update({ is_visible: false }).eq('id', id); setData(d => ({ ...d, reviews: d.reviews.filter(r => r.id !== id) })) }
  const toggleCampaign = async (c) => { const upd = { ...c, is_active: !c.is_active }; await sb().from('salon_campaigns').update({ is_active: upd.is_active }).eq('id', c.id); setData(d => ({ ...d, campaigns: d.campaigns.map(x => x.id === c.id ? upd : x) })) }
  const updateApptStatus = async (id, status) => { await sb().from('appointments').update({ status }).eq('id', id); setData(d => ({ ...d, appointments: d.appointments.map(a => a.id === id ? { ...a, status } : a) })) }
  const loadClientHistory = async (client) => { setSelectedClient(client); const { data: appts } = await sb().from('appointments').select('*').eq('salon_id', salon.id).eq('client_phone', client.phone).order('appointment_date', { ascending: false }).limit(50); setClientHistory(appts || []) }
  const saveSchedule = async () => { await sb().from('salons').update({ schedule_settings: scheduleSettings }).eq('id', salon.id); const u = { ...salon, schedule_settings: scheduleSettings }; setSalon(u); localStorage.setItem('sm_salon', JSON.stringify(u)); alert('Schedule saved!') }
  const addService = async () => { if (!newService.name.trim()) return; const { data: ins } = await sb().from('salon_services').insert([{ salon_id: salon.id, ...newService }]).select(); if (ins) setData(d => ({ ...d, services: [...d.services, ...ins] })); setNewService({ name: '', category: 'Haircuts', duration: 45, price: 0, sort_order: 0 }) }
  const deleteService = async (id) => { if (!window.confirm('Delete this service?')) return; await sb().from('salon_services').delete().eq('id', id); setData(d => ({ ...d, services: d.services.filter(s => s.id !== id) })) }
  const updateService = async (svc) => { await sb().from('salon_services').update({ name: svc.name, category: svc.category, duration: svc.duration, price: svc.price, sort_order: svc.sort_order }).eq('id', svc.id); setData(d => ({ ...d, services: d.services.map(s => s.id === svc.id ? svc : s) })); setEditingService(null) }
  const saveCustomAutomation = async () => { if (!customAutomation.name.trim() || !customAutomation.message.trim()) return; const { data: ins } = await sb().from('salon_campaigns').insert([{ salon_id: salon.id, name: customAutomation.name, campaign_type: customAutomation.trigger, message_template: customAutomation.message, is_active: true }]).select(); if (ins) setData(d => ({ ...d, campaigns: [...d.campaigns, ...ins] })); setCustomAutomation({ name: '', trigger: 'after_booking', message: '', delay_hours: 0 }); setShowCustomAutomation(false) }
  const saveSettings = async () => { await sb().from('salons').update(settingsForm).eq('id', salon.id); const u = { ...salon, ...settingsForm }; setSalon(u); localStorage.setItem('sm_salon', JSON.stringify(u)); alert('Settings saved!') }
  const askAi = async (overrideQuery) => {
        const query = overrideQuery || aiQuery; if (!query.trim()) return; setAiLoading(true); setAiResponse('')
        const { appointments, reviews, clients, campaigns } = data; const today = new Date().toISOString().split('T')[0]
        const todayCount = appointments.filter(a => a.appointment_date === today).length
        const rev = appointments.filter(a => a.status === 'completed').reduce((s, a) => s + (a.total_price || 0), 0)
        const avgR = reviews.length > 0 ? (reviews.reduce((s, r) => s + r.stars, 0) / reviews.length).toFixed(1) : 'none'
        const ctx = `Shop: ${salon.shop_name} | Owner: ${salon.owner_name} | Type: ${salon.salon_type} | City: ${salon.city}, ${salon.state} | Today: ${todayCount} appts | Clients: ${clients.length} | Revenue: $${rev} | Avg rating: ${avgR} | Active automations: ${campaigns.filter(c => c.is_active).length}`
        try {
                const res = await fetch('https://api.anthropic.com/v1/messages', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ model: 'claude-sonnet-4-20250514', max_tokens: 1000, system: `You are the AI business advisor for ${salon.shop_name}, a ${salon.salon_type} in ${salon.city}, ${salon.state}. Give direct, actionable advice. Context: ${ctx}`, messages: [{ role: 'user', content: query }] }) })
                const d = await res.json(); setAiResponse(d.content?.map(c => c.text || '').join('') || 'Unable to respond.')
                await sb().from('ai_conversations').insert([{ salon_id: salon.id, type: 'advisor', channel: 'web', messages: [{ role: 'user', content: query }, { role: 'assistant', content: d.content?.map(c => c.text || '').join('') }], resolved: true }])
        } catch { setAiResponse('AI advisor is temporarily unavailable.') }
        setAiLoading(false)
  }

  const { appointments, reviews, clients, campaigns, services } = data
  const today = new Date().toISOString().split('T')[0]
  const todayAppts = appointments.filter(a => a.appointment_date === today)
  const revenue = appointments.filter(a => a.status === 'completed').reduce((s, a) => s + (a.total_price || 0), 0)
  const avgRating = reviews.length > 0 ? (reviews.reduce((s, r) => s + r.stars, 0) / reviews.length).toFixed(1) : '\u2014'
  const statusColor = { confirmed: 'var(--gold)', completed: 'var(--green)', cancelled: 'var(--red)', no_show: 'var(--muted)', pending: 'var(--blue)' }
  const dayNames = { mon: 'Monday', tue: 'Tuesday', wed: 'Wednesday', thu: 'Thursday', fri: 'Friday', sat: 'Saturday', sun: 'Sunday' }
  const timeAgo = (d) => { if (!d) return ''; const s = Math.floor((Date.now() - new Date(d)) / 1000); if (s < 60) return 'just now'; if (s < 3600) return Math.floor(s/60) + 'm ago'; if (s < 86400) return Math.floor(s/3600) + 'h ago'; return Math.floor(s/86400) + 'd ago' }
  const Dot = ({ on }) => <div style={{ width: 7, height: 7, borderRadius: '50%', background: on ? 'var(--green)' : 'var(--muted)', flexShrink: 0 }} />
  const Badge = ({ text, color = 'var(--gold)' }) => <span style={{ fontSize: 9, letterSpacing: '.12em', textTransform: 'uppercase', color, border: `1px solid ${color}`, padding: '2px 8px', opacity: .9 }}>{text}</span>
  const Empty = ({ main, sub }) => (<div style={{ border: '1px dashed var(--border-dim)', padding: '80px 32px', textAlign: 'center' }}><div className="cormorant" style={{ fontSize: 22, fontStyle: 'italic', color: 'var(--muted)', marginBottom: 8 }}>{main}</div><div style={{ fontSize: 12, color: 'var(--muted)', opacity: .6 }}>{sub}</div></div>)
  const Stat = ({ label, value, sub, accent }) => (<div style={{ background: 'var(--dark-2)', padding: '26px', border: '1px solid var(--border-dim)', flex: 1, minWidth: 0 }}><div style={{ fontSize: 10, letterSpacing: '.25em', textTransform: 'uppercase', color: 'var(--muted)', marginBottom: 12 }}>{label}</div><div className="cormorant" style={{ fontSize: 44, fontWeight: 300, color: accent || 'var(--gold)', lineHeight: 1 }}>{value}</div>{sub && <div style={{ fontSize: 11, color: 'var(--muted)', marginTop: 6 }}>{sub}</div>}</div>)
      const serviceCategories = [...new Set(services.map(s => s.category))].filter(Boolean)

  return (
        <div style={{ minHeight: '100vh', display: 'flex', background: 'var(--black)' }}>
      <div style={{ width: 240, background: 'var(--dark)', borderRight: '1px solid var(--border-dim)', display: 'flex', flexDirection: 'column', flexShrink: 0 }}>
        <div style={{ padding: '28px 24px', borderBottom: '1px solid var(--border-dim)' }}>
          <div className="cinzel" style={{ fontSize: 13, letterSpacing: '.3em', color: 'var(--gold)', marginBottom: 4 }}>ServiceMind</div>
          <div style={{ fontSize: 9, letterSpacing: '.2em', textTransform: 'uppercase', color: 'var(--muted)' }}>Salon Dashboard</div>
    </div>
        <div style={{ padding: '16px 0', flex: 1, overflowY: 'auto' }}>
{NAV.map(n => (<button key={n.id} onClick={() => setTab(n.id)} style={{ display: 'block', width: '100%', textAlign: 'left', padding: '13px 24px', background: tab === n.id ? 'rgba(201,168,76,.07)' : 'transparent', border: 'none', borderLeft: `2px solid ${tab === n.id ? 'var(--gold)' : 'transparent'}`, color: tab === n.id ? 'var(--gold)' : 'var(--muted)', fontSize: 11, letterSpacing: '.15em', textTransform: 'uppercase', cursor: 'pointer', transition: 'all .15s' }}>{n.label}</button>))}
  </div>
        <div style={{ padding: '20px 24px', borderTop: '1px solid var(--border-dim)' }}>
          <div style={{ fontSize: 14, color: 'var(--text)', marginBottom: 3 }}>{salon.shop_name}</div>
          <div style={{ fontSize: 11, color: 'var(--muted)', marginBottom: 14 }}>{salon.owner_name}</div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 16 }}><Dot on={salon.subscription_status === 'active' || salon.subscription_status === 'trial'} /><span style={{ fontSize: 10, color: 'var(--muted)', letterSpacing: '.15em', textTransform: 'uppercase' }}>{salon.subscription_status}</span></div>
          <button onClick={() => { localStorage.removeItem('sm_salon'); router.push('/') }} className="btn-ghost" style={{ padding: '8px 16px', fontSize: 9, width: '100%', textAlign: 'center' }}>Log Out</button>
  </div>
  </div>
      <div style={{ flex: 1, overflowY: 'auto' }}>
        <div style={{ padding: '20px 48px', borderBottom: '1px solid var(--border-dim)', display: 'flex', alignItems: 'center', justifyContent: 'space-between', background: 'var(--black)', position: 'sticky', top: 0, zIndex: 10 }}>
          <div><div className="cinzel" style={{ fontSize: 14, letterSpacing: '.2em', color: 'var(--text)' }}>{NAV.find(n => n.id === tab)?.label}</div><div style={{ fontSize: 11, color: 'var(--muted)', marginTop: 2 }}>{new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' })}</div></div>
          <div style={{ display: 'flex', gap: 12, alignItems: 'center' }}>{salon.phone && <span style={{ fontSize: 12, color: 'var(--muted)' }}>{salon.phone}</span>}<a href={`/book/${salon.slug}`} target="_blank" rel="noreferrer" className="cinzel" style={{ fontSize: 10, letterSpacing: '.15em', color: 'var(--gold)', border: '1px solid var(--border)', padding: '8px 16px', textDecoration: 'none' }}>Booking Page &rarr;</a></div>
                  </div>
                          <div style={{ padding: '48px' }}>
                                    {loading && <div className="cinzel" style={{ textAlign: 'center', color: 'var(--muted)', padding: 80, letterSpacing: '.2em', fontSize: 11 }}>Loading...</div>}

                                              {!loading && tab === 'overview' && (<div>
                                                          <div style={{ display: 'flex', gap: 2, marginBottom: 44 }}><Stat label="Today's Appointments" value={todayAppts.length} sub={`${appointments.length} total all time`} /><Stat label="Total Clients" value={clients.length} sub="in your database" /><Stat label="Avg Rating" value={avgRating} sub={`${reviews.length} reviews`} /><Stat label="Revenue Tracked" value={`$${revenue.toLocaleString()}`} sub="completed appointments" /></div>
                                                                      <div style={{ display: 'grid', gridTemplateColumns: '1.4fr 1fr', gap: 2 }}>
                                                                                    <div><div className="cinzel" style={{ fontSize: 10, letterSpacing: '.25em', color: 'var(--gold)', marginBottom: 16, display: 'flex', alignItems: 'center', gap: 12 }}>Today&apos;s Schedule <span style={{ flex: 1, height: 1, background: 'var(--border-dim)' }} /></div>
                                                                                                    {todayAppts.length === 0 ? <Empty main="No appointments today" sub="Bookings from your site appear here automatically." /> : todayAppts.map(a => (<div key={a.id} className="card" style={{ padding: '18px 22px', marginBottom: 2, display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}><div><div style={{ fontSize: 14, color: 'var(--text)', marginBottom: 3 }}>{a.client_name}</div><div style={{ fontSize: 11, color: 'var(--muted)' }}>{a.service_name} &middot; {a.appointment_time} &middot; <span style={{ color: 'var(--gold)' }}>${a.total_price}</span></div></div><Badge text={a.status} color={statusColor[a.status] || 'var(--muted)'} /></div>))}
                                                                                                                  </div>
                                                                                                                                <div style={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
                                                                                                                                                <div className="card" style={{ padding: '28px', flex: 1 }}><div className="cinzel" style={{ fontSize: 10, letterSpacing: '.2em', color: 'var(--gold)', marginBottom: 16 }}>Automations</div>{campaigns.slice(0, 6).map(c => (<div key={c.id} style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 10 }}><Dot on={c.is_active} /><span style={{ fontSize: 12, color: c.is_active ? 'var(--text)' : 'var(--muted)' }}>{c.name}</span></div>))}</div>
                                                                                                                                                                <div className="card" style={{ padding: '28px' }}><div className="cinzel" style={{ fontSize: 10, letterSpacing: '.2em', color: 'var(--gold)', marginBottom: 16 }}>Shop Details</div>{[['Type', salon.salon_type], ['City', [salon.city, salon.state].filter(Boolean).join(', ') || '\u2014'], ['Plan', salon.subscription_tier], ['Status', salon.subscription_status]].map(([l, v]) => (<div key={l} style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 10, fontSize: 12 }}><span style={{ color: 'var(--muted)' }}>{l}</span><span style={{ color: 'var(--text)', textTransform: 'capitalize' }}>{v}</span></div>))}</div>
                                                                                                                                                                              </div>
                                                                                                                                                                                          </div>
                                                                                                                                                                                                    </div>)}
                                                                                                                                                                                                    
                                                                                                                                                                                                              {!loading && tab === 'appointments' && (<div>
                                                                                                                                                                                                                          <div style={{ fontSize: 13, color: 'var(--muted)', marginBottom: 32 }}>{appointments.length} total &middot; {todayAppts.length} today</div>
                                                                                                                                                                                                                                      {appointments.length === 0 ? <Empty main="No appointments yet" sub="Bookings through your site appear here automatically." /> : appointments.map(a => (<div key={a.id} className="card" style={{ padding: '18px 24px', marginBottom: 2, display: 'flex', alignItems: 'center', gap: 16, justifyContent: 'space-between' }}><div style={{ flex: 1 }}><div style={{ fontSize: 14, color: 'var(--text)', marginBottom: 4 }}>{a.client_name}</div><div style={{ fontSize: 11, color: 'var(--muted)' }}>{a.service_name} &middot; {a.appointment_date} at {a.appointment_time} &middot; <span style={{ color: 'var(--gold)' }}>${a.total_price}</span></div>{a.client_phone && <div style={{ fontSize: 11, color: 'var(--muted)', marginTop: 2 }}>{a.client_phone}</div>}</div><select style={{ background: 'var(--dark-3)', border: '1px solid var(--border-dim)', color: 'var(--text)', padding: '8px 12px', fontSize: 11, outline: 'none', borderRadius: 0, cursor: 'pointer' }} value={a.status} onChange={e => updateApptStatus(a.id, e.target.value)}><option value="confirmed">Confirmed</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option><option value="no_show">No Show</option></select></div>))}
                                                                                                                                                                                                                                                </div>)}
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                          {!loading && tab === 'clients' && (<div>
                                                                                                                                                                                                                                                                      <div style={{ fontSize: 13, color: 'var(--muted)', marginBottom: 32 }}>{clients.length} clients in your database</div>
                                                                                                                                                                                                                                                                                  {selectedClient ? (<div>
                                                                                                                                                                                                                                                                                                <button onClick={() => { setSelectedClient(null); setClientHistory([]) }} style={{ background: 'transparent', border: 'none', color: 'var(--muted)', fontSize: 12, cursor: 'pointer', marginBottom: 20 }}>&larr; Back to all clients</button>
                                                                                                                                                                                                                                                                                                              <div className="card-gold" style={{ padding: '32px', marginBottom: 20, position: 'relative' }}><div className="gold-line-top" /><div style={{ display: 'flex', alignItems: 'center', gap: 20 }}><div style={{ width: 60, height: 60, borderRadius: '50%', background: 'linear-gradient(135deg, rgba(201,168,76,.3), var(--dark-3))', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 24, color: 'var(--gold)', fontFamily: 'Cinzel' }}>{(selectedClient.name || 'C').charAt(0).toUpperCase()}</div><div><div style={{ fontSize: 20, color: 'var(--text)', marginBottom: 4 }}>{selectedClient.name}</div><div style={{ fontSize: 13, color: 'var(--muted)' }}>{selectedClient.phone || 'No phone'}</div><div style={{ fontSize: 12, color: 'var(--muted)', marginTop: 4 }}>{selectedClient.total_visits} visits &middot; <span style={{ color: 'var(--gold)' }}>${selectedClient.total_spent} spent</span></div></div></div></div>
                                                                                                                                                                                                                                                                                                                            <div className="cinzel" style={{ fontSize: 10, letterSpacing: '.25em', color: 'var(--gold)', marginBottom: 16 }}>Visit History</div>
                                                                                                                                                                                                                                                                                                                                          {clientHistory.length === 0 ? <Empty main="No visit history" sub="Appointment records will appear here." /> : clientHistory.map(a => (<div key={a.id} className="card" style={{ padding: '16px 24px', marginBottom: 2, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}><div><div style={{ fontSize: 13, color: 'var(--text)' }}>{a.service_name}</div><div style={{ fontSize: 11, color: 'var(--muted)' }}>{a.appointment_date} at {a.appointment_time}</div></div><div style={{ textAlign: 'right' }}><div style={{ fontSize: 13, color: 'var(--gold)' }}>${a.total_price}</div><Badge text={a.status} color={statusColor[a.status] || 'var(--muted)'} /></div></div>))}
                                                                                                                                                                                                                                                                                                                                                      </div>) : (clients.length === 0 ? <Empty main="No clients yet" sub="Every person who books appears here automatically." /> : <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2,1fr)', gap: 2 }}>{clients.map(c => (<div key={c.id} className="card" style={{ padding: '20px 24px', display: 'flex', alignItems: 'center', gap: 14, cursor: 'pointer' }} onClick={() => loadClientHistory(c)}><div style={{ width: 40, height: 40, borderRadius: '50%', background: 'linear-gradient(135deg, rgba(201,168,76,.3), var(--dark-3))', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 15, color: 'var(--gold)', fontFamily: 'Cinzel' }}>{(c.name || 'C').charAt(0).toUpperCase()}</div><div style={{ flex: 1, minWidth: 0 }}><div style={{ fontSize: 13, color: 'var(--text)', marginBottom: 3 }}>{c.name || 'Unknown'}</div><div style={{ fontSize: 11, color: 'var(--muted)' }}>{c.phone || 'No phone'} &middot; {c.total_visits} visits &middot; <span style={{ color: 'var(--gold)' }}>${c.total_spent}</span></div></div>{c.last_visit_at && <div style={{ fontSize: 10, color: 'var(--muted)' }}>{new Date(c.last_visit_at).toLocaleDateString()}</div>}</div>))}</div>)}
                                                                                                                                                                                                                                                                                                                                                                </div>)}
                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                          {!loading && tab === 'reviews' && (<div>
                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ fontSize: 13, color: 'var(--muted)', marginBottom: 32 }}>{reviews.length} reviews &middot; {avgRating}&star; average &middot; <span style={{ color: 'var(--gold)' }}>You can remove any review</span></div>
                                                                                                                                                                                                                                                                                                                                                                                                  {reviews.length === 0 ? <Empty main="No reviews yet" sub="Reviews submitted on your booking site appear here." /> : <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2,1fr)', gap: 2 }}>{reviews.map(r => (<div key={r.id} className="card" style={{ padding: '28px', position: 'relative' }}><button onClick={() => deleteReview(r.id)} style={{ position: 'absolute', top: 14, right: 14, background: 'rgba(192,57,43,.08)', border: '1px solid rgba(192,57,43,.2)', color: 'var(--red)', fontSize: 9, letterSpacing: '.12em', textTransform: 'uppercase', padding: '4px 10px', cursor: 'pointer' }}>Remove</button><div style={{ color: 'var(--gold)', fontSize: 12, letterSpacing: 3, marginBottom: 12 }}>{'&#9733;'.repeat(r.stars)}{'&#9734;'.repeat(5 - r.stars)}</div><div className="cormorant" style={{ fontSize: 16, fontStyle: 'italic', lineHeight: 1.7, color: 'var(--text)', marginBottom: 14 }}>&quot;{r.review_text}&quot;</div><div style={{ fontSize: 11, color: 'var(--muted)' }}>{r.author_name} &middot; {r.service_received} &middot; {new Date(r.created_at).toLocaleDateString()}</div></div>))}</div>}
                                                                                                                                                                                                                                                                                                                                                                                                            </div>)}
                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                      {!loading && tab === 'campaigns' && (<div>
                                                                                                                                                                                                                                                                                                                                                                                                                                  <div style={{ fontSize: 13, color: 'var(--muted)', lineHeight: 1.8, marginBottom: 24 }}>Toggle automations on/off. When enabled, messages go out via SMS. Variables like <span style={{ color: 'var(--gold)' }}>{'{{shop_name}}'}</span> are filled automatically.</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                              <button onClick={() => setShowCustomAutomation(!showCustomAutomation)} className="btn-gold" style={{ padding: '12px 24px', fontSize: 10, marginBottom: 24 }}>{showCustomAutomation ? 'Cancel' : '+ Create Custom Automation'}</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          {showCustomAutomation && (<div className="card-gold" style={{ padding: '28px', marginBottom: 24, position: 'relative' }}><div className="gold-line-top" /><div className="cinzel" style={{ fontSize: 10, letterSpacing: '.2em', color: 'var(--gold)', marginBottom: 16 }}>New Automation</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12, marginBottom: 12 }}><div><label style={{ fontSize: 10, letterSpacing: '.2em', textTransform: 'uppercase', color: 'var(--muted)', display: 'block', marginBottom: 6 }}>Name</label><input className="input" value={customAutomation.name} onChange={e => setCustomAutomation(p => ({ ...p, name: e.target.value }))} placeholder="e.g. Welcome Text" /></div><div><label style={{ fontSize: 10, letterSpacing: '.2em', textTransform: 'uppercase', color: 'var(--muted)', display: 'block', marginBottom: 6 }}>Trigger</label><select className="input" value={customAutomation.trigger} onChange={e => setCustomAutomation(p => ({ ...p, trigger: e.target.value }))}><option value="after_booking">After Booking</option><option value="missed_call">Missed Call</option><option value="no_show">No Show</option><option value="birthday">Birthday</option><option value="win_back">Win Back</option><option value="slow_day">Slow Day</option><option value="custom">Custom</option></select></div></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ marginBottom: 12 }}><label style={{ fontSize: 10, letterSpacing: '.2em', textTransform: 'uppercase', color: 'var(--muted)', display: 'block', marginBottom: 6 }}>Message Template</label><textarea className="input" rows={3} value={customAutomation.message} onChange={e => setCustomAutomation(p => ({ ...p, message: e.target.value }))} placeholder="Hey {{client_name}}! ..." style={{ resize: 'vertical' }} /></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div style={{ fontSize: 11, color: 'var(--muted)', marginBottom: 16 }}>Variables: {'{{client_name}}, {{shop_name}}, {{booking_link}}, {{review_link}}, {{time}}'}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button onClick={saveCustomAutomation} className="btn-gold" style={{ padding: '12px 24px', fontSize: 10 }}>Save Automation</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div style={{ display: 'flex', flexDirection: 'column', gap: 2 }}>{campaigns.map(c => (<div key={c.id} style={{ background: 'var(--dark)', border: `1px solid ${c.is_active ? 'var(--border)' : 'var(--border-dim)'}`, padding: '22px 28px' }}><div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: c.message_template ? 12 : 0 }}><div style={{ display: 'flex', alignItems: 'center', gap: 14 }}><Dot on={c.is_active} /><div><div style={{ fontSize: 13, color: 'var(--text)', marginBottom: 2 }}>{c.name}</div><div style={{ fontSize: 10, color: 'var(--muted)', letterSpacing: '.12em', textTransform: 'uppercase' }}>{c.campaign_type.replace(/_/g, ' ')}</div></div></div><button onClick={() => toggleCampaign(c)} className={c.is_active ? 'btn-ghost' : 'btn-gold'} style={{ padding: '8px 20px', fontSize: 10 }}>{c.is_active ? 'Disable' : 'Enable'}</button></div>{c.message_template && (<div style={{ background: 'var(--dark-3)', border: '1px solid var(--border-dim)', padding: '12px 16px', fontSize: 12, color: 'var(--muted)', lineHeight: 1.7, marginLeft: 22, fontStyle: 'italic' }}>&quot;{c.message_template}&quot;</div>)}</div>))}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>)}

            {!loading && tab === 'conversations' && (<div>
                        <div style={{ display: 'grid', gridTemplateColumns: '280px 1fr', gap: 2, minHeight: 500 }}>
                                      <div style={{ background: 'var(--dark)', border: '1px solid var(--border-dim)', overflowY: 'auto' }}>
                                                      <div className="cinzel" style={{ fontSize: 10, letterSpacing: '.2em', color: 'var(--gold)', padding: '16px 20px', borderBottom: '1px solid var(--border-dim)' }}>Clients</div>
                                                                      {conversations.length === 0 ? <div style={{ padding: 20, fontSize: 12, color: 'var(--muted)' }}>No clients yet</div> : conversations.map((cv, i) => (<div key={i} onClick={() => setSelectedConvo(cv)} style={{ padding: '14px 20px', borderBottom: '1px solid var(--border-dim)', cursor: 'pointer', background: selectedConvo?.client?.id === cv.client.id ? 'rgba(201,168,76,.07)' : 'transparent' }}><div style={{ fontSize: 13, color: 'var(--text)', marginBottom: 2 }}>{cv.client.name}</div><div style={{ fontSize: 11, color: 'var(--muted)' }}>{cv.client.phone}</div><div style={{ fontSize: 10, color: 'var(--muted)', marginTop: 4 }}>{cv.lastMessage}</div></div>))}
                                                                                    </div>
                                                                                                  <div style={{ background: 'var(--dark)', border: '1px solid var(--border-dim)', display: 'flex', flexDirection: 'column' }}>
                                                                                                                  {!selectedConvo ? <div style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center' }}><Empty main="Select a client" sub="Click a client to view conversation" /></div> : (<>
                                                                                                                                    <div style={{ padding: '16px 24px', borderBottom: '1px solid var(--border-dim)', display: 'flex', alignItems: 'center', gap: 12 }}><div style={{ width: 36, height: 36, borderRadius: '50%', background: 'linear-gradient(135deg, rgba(201,168,76,.3), var(--dark-3))', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 14, color: 'var(--gold)', fontFamily: 'Cinzel' }}>{(selectedConvo.client.name || 'C').charAt(0).toUpperCase()}</div><div><div style={{ fontSize: 14, color: 'var(--text)' }}>{selectedConvo.client.name}</div><div style={{ fontSize: 11, color: 'var(--muted)' }}>{selectedConvo.client.phone}</div></div></div>
                                                                                                                                                      <div style={{ flex: 1, padding: 24, overflowY: 'auto' }}>{selectedConvo.messages.length === 0 ? <div style={{ textAlign: 'center', color: 'var(--muted)', fontSize: 12, marginTop: 60 }}>No messages yet. Start a conversation below.</div> : selectedConvo.messages.map((m, i) => (<div key={i} style={{ marginBottom: 12, textAlign: m.role === 'shop' ? 'right' : 'left' }}><div style={{ display: 'inline-block', padding: '10px 16px', background: m.role === 'shop' ? 'var(--gold-muted)' : 'var(--dark-3)', border: '1px solid var(--border-dim)', maxWidth: '70%', fontSize: 13, color: 'var(--text)' }}>{m.text}</div></div>))}</div>
                                                                                                                                                                        <div style={{ padding: '16px 24px', borderTop: '1px solid var(--border-dim)', display: 'flex', gap: 8 }}><input className="input" placeholder="Type a message..." value={convoReply} onChange={e => setConvoReply(e.target.value)} style={{ flex: 1 }} /><button className="btn-gold" style={{ padding: '14px 24px', fontSize: 10 }} onClick={() => { if (!convoReply.trim()) return; setConversations(prev => prev.map(cv => cv.client.id === selectedConvo.client.id ? { ...cv, messages: [...cv.messages, { role: 'shop', text: convoReply }] } : cv)); setSelectedConvo(p => ({ ...p, messages: [...p.messages, { role: 'shop', text: convoReply }] })); setConvoReply('') }}>Send</button></div>
                                                                                                                                                                                        </>)}
                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                            </div>)}
                                                                                                                                                                                                                            
                                                                                                                                                                                                                                      {!loading && tab === 'services' && (<div>
                                                                                                                                                                                                                                                  <div className="card-gold" style={{ padding: '28px', marginBottom: 24, position: 'relative' }}><div className="gold-line-top" /><div className="cinzel" style={{ fontSize: 10, letterSpacing: '.2em', color: 'var(--gold)', marginBottom: 16 }}>Add New Service</div>
                                                                                                                                                                                                                                                                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 80px 80px 80px', gap: 12, alignItems: 'end' }}>
                                                                                                                                                                                                                                                                                <div><label style={{ fontSize: 10, letterSpacing: '.2em', textTransform: 'uppercase', color: 'var(--muted)', display: 'block', marginBottom: 6 }}>Name</label><input className="input" value={newService.name} onChange={e => setNewService(p => ({ ...p, name: e.target.value }))} placeholder="e.g. Taper Fade" /></div>
                                                                                                                                                                                                                                                                                                <div><label style={{ fontSize: 10, letterSpacing: '.2em', textTransform: 'uppercase', color: 'var(--muted)', display: 'block', marginBottom: 6 }}>Category</label><input className="input" value={newService.category} onChange={e => setNewService(p => ({ ...p, category: e.target.value }))} placeholder="Haircuts" /></div>
                                                                                                                                                                                                                                                                                                                <div><label style={{ fontSize: 10, letterSpacing: '.2em', textTransform: 'uppercase', color: 'var(--muted)', display: 'block', marginBottom: 6 }}>Min</label><input className="input" type="number" value={newService.duration} onChange={e => setNewService(p => ({ ...p, duration: +e.target.value }))} /></div>
                                                                                                                                                                                                                                                                                                                                <div><label style={{ fontSize: 10, letterSpacing: '.2em', textTransform: 'uppercase', color: 'var(--muted)', display: 'block', marginBottom: 6 }}>Price</label><input className="input" type="number" value={newService.price} onChange={e => setNewService(p => ({ ...p, price: +e.target.value }))} /></div>
                                                                                                                                                                                                                                                                                                                                                <button onClick={addService} className="btn-gold" style={{ padding: '14px 16px', fontSize: 10 }}>Add</button>
                                                                                                                                                                                                                                                                                                                                                              </div>
              </div>
                          {serviceCategories.length === 0 && services.length === 0 ? <Empty main="No services yet" sub="Add your first service above." /> : serviceCategories.map(cat => (<div key={cat} style={{ marginBottom: 24 }}><div className="cinzel" style={{ fontSize: 10, letterSpacing: '.25em', color: 'var(--gold)', marginBottom: 12, display: 'flex', alignItems: 'center', gap: 12 }}>{cat} <span style={{ flex: 1, height: 1, background: 'var(--border-dim)' }} /></div>{services.filter(s => s.category === cat).map(s => (<div key={s.id} className="card" style={{ padding: '16px 24px', marginBottom: 2, display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>{editingService?.id === s.id ? (<><input className="input" value={editingService.name} onChange={e => setEditingService(p => ({ ...p, name: e.target.value }))} style={{ width: 160, padding: '8px 12px' }} /><input className="input" type="number" value={editingService.duration} onChange={e => setEditingService(p => ({ ...p, duration: +e.target.value }))} style={{ width: 60, padding: '8px 12px' }} /><input className="input" type="number" value={editingService.price} onChange={e => setEditingService(p => ({ ...p, price: +e.target.value }))} style={{ width: 70, padding: '8px 12px' }} /><button onClick={() => updateService(editingService)} className="btn-gold" style={{ padding: '8px 16px', fontSize: 9 }}>Save</button><button onClick={() => setEditingService(null)} className="btn-ghost" style={{ padding: '8px 12px', fontSize: 9 }}>Cancel</button></>) : (<><div><div style={{ fontSize: 13, color: 'var(--text)' }}>{s.name}</div><div style={{ fontSize: 11, color: 'var(--muted)' }}>{s.duration} min</div></div><div style={{ display: 'flex', alignItems: 'center', gap: 12 }}><span style={{ fontSize: 14, color: 'var(--gold)' }}>${s.price}</span><button onClick={() => setEditingService({ ...s })} className="btn-ghost" style={{ padding: '6px 12px', fontSize: 9 }}>Edit</button><button onClick={() => deleteService(s.id)} style={{ background: 'rgba(192,57,43,.08)', border: '1px solid rgba(192,57,43,.2)', color: 'var(--red)', fontSize: 9, padding: '6px 12px', cursor: 'pointer' }}>Delete</button></div></>)}</div>))}</div>))}
                                    </div>)}

                                              {!loading && tab === 'schedule' && (<div>
                                                          <div className="card-gold" style={{ padding: '36px', marginBottom: 20, position: 'relative' }}><div className="gold-line-top" /><div className="eyebrow" style={{ marginBottom: 20 }}>Working Hours</div>
                                                                        <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>{Object.entries(dayNames).map(([key, name]) => (<div key={key} style={{ display: 'flex', alignItems: 'center', gap: 16, padding: '10px 0' }}><label style={{ width: 110, fontSize: 13, color: scheduleSettings[key]?.enabled ? 'var(--text)' : 'var(--muted)' }}><input type="checkbox" checked={scheduleSettings[key]?.enabled || false} onChange={e => setScheduleSettings(p => ({ ...p, [key]: { ...p[key], enabled: e.target.checked } }))} style={{ marginRight: 10 }} />{name}</label>{scheduleSettings[key]?.enabled && (<><input type="time" className="input" value={scheduleSettings[key]?.open || '08:00'} onChange={e => setScheduleSettings(p => ({ ...p, [key]: { ...p[key], open: e.target.value } }))} style={{ width: 130, padding: '8px 12px' }} /><span style={{ color: 'var(--muted)' }}>to</span><input type="time" className="input" value={scheduleSettings[key]?.close || '18:00'} onChange={e => setScheduleSettings(p => ({ ...p, [key]: { ...p[key], close: e.target.value } }))} style={{ width: 130, padding: '8px 12px' }} /></>)}</div>))}</div>
                                                                                    </div>
                                                                                                <div className="card" style={{ padding: '28px', marginBottom: 20 }}><div className="cinzel" style={{ fontSize: 10, letterSpacing: '.2em', color: 'var(--gold)', marginBottom: 16 }}>Slot Settings</div>
                                                                                                              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
                                                                                                                              <div><label style={{ fontSize: 10, letterSpacing: '.2em', textTransform: 'uppercase', color: 'var(--muted)', display: 'block', marginBottom: 6 }}>Slot Duration (minutes)</label><select className="input" value={scheduleSettings.slot_duration} onChange={e => setScheduleSettings(p => ({ ...p, slot_duration: +e.target.value }))}><option value={15}>15 min</option><option value={30}>30 min</option><option value={45}>45 min</option><option value={60}>60 min</option></select></div>
                                                                                                                                              <div><label style={{ fontSize: 10, letterSpacing: '.2em', textTransform: 'uppercase', color: 'var(--muted)', display: 'block', marginBottom: 6 }}>Buffer Between Appointments</label><select className="input" value={scheduleSettings.buffer_minutes} onChange={e => setScheduleSettings(p => ({ ...p, buffer_minutes: +e.target.value }))}><option value={0}>No buffer</option><option value={5}>5 min</option><option value={10}>10 min</option><option value={15}>15 min</option><option value={30}>30 min</option></select></div>
                                                                                                                                                            </div>
                                                                                                                                                                        </div>
                                                                                                                                                                                    <div className="card" style={{ padding: '28px', marginBottom: 20 }}><div className="cinzel" style={{ fontSize: 10, letterSpacing: '.2em', color: 'var(--gold)', marginBottom: 16 }}>Blocked Dates</div>
                                                                                                                                                                                                  <div style={{ display: 'flex', gap: 8, marginBottom: 16 }}><input type="date" className="input" value={blockDate} onChange={e => setBlockDate(e.target.value)} style={{ width: 200 }} /><button onClick={() => { if (blockDate && !scheduleSettings.blocked_dates.includes(blockDate)) { setScheduleSettings(p => ({ ...p, blocked_dates: [...p.blocked_dates, blockDate] })); setBlockDate('') } }} className="btn-gold" style={{ padding: '12px 20px', fontSize: 10 }}>Block Date</button></div>
                                                                                                                                                                                                                {scheduleSettings.blocked_dates?.length > 0 && <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8 }}>{scheduleSettings.blocked_dates.map(d => (<span key={d} style={{ background: 'var(--dark-3)', border: '1px solid var(--border-dim)', padding: '6px 12px', fontSize: 11, color: 'var(--text)', display: 'flex', alignItems: 'center', gap: 8 }}>{d}<button onClick={() => setScheduleSettings(p => ({ ...p, blocked_dates: p.blocked_dates.filter(x => x !== d) }))} style={{ background: 'none', border: 'none', color: 'var(--red)', cursor: 'pointer', fontSize: 14 }}>&times;</button></span>))}</div>}
                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                        <button onClick={saveSchedule} className="btn-gold" style={{ padding: '15px 36px' }}>Save Schedule</button>
                                                                                                                                                                                                                                                  </div>)}
                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                            {!loading && tab === 'ai' && (<div>
                                                                                                                                                                                                                                                                        <div style={{ background: 'var(--dark)', border: '1px solid var(--border)', padding: '36px', marginBottom: 24, position: 'relative' }}><div className="gold-line-top" /><div className="eyebrow" style={{ marginBottom: 20 }}>AI Business Advisor</div><h3 className="cormorant" style={{ fontSize: 36, fontWeight: 300, marginBottom: 16 }}>Ask your <em style={{ color: 'var(--gold)', fontStyle: 'italic' }}>AI advisor</em> anything.</h3><p style={{ fontSize: 13, color: 'var(--muted)', lineHeight: 1.8, marginBottom: 28 }}>Your AI knows your shop &mdash; its revenue, appointment patterns, client base, and ratings.</p>
                                                                                                                                                                                                                                                                                      <div style={{ display: 'flex', gap: 8 }}><input className="input" placeholder="e.g. How can I increase revenue this month?" value={aiQuery} onChange={e => setAiQuery(e.target.value)} onKeyDown={e => e.key === 'Enter' && askAi()} style={{ flex: 1 }} /><button onClick={() => askAi()} disabled={aiLoading || !aiQuery.trim()} className="btn-gold" style={{ padding: '14px 28px', opacity: aiLoading || !aiQuery.trim() ? .5 : 1 }}>{aiLoading ? '...' : 'Ask \u2192'}</button></div>
                                                                                                                                                                                                                                                                                                    <div style={{ display: 'flex', gap: 8, marginTop: 14, flexWrap: 'wrap' }}>{['What should I focus on this week?', 'Why are my no-shows high?', 'How do I get more clients?', 'Write me a slow day promo text'].map(q => (<button key={q} onClick={() => { setAiQuery(q); askAi(q) }} style={{ background: 'transparent', border: '1px solid var(--border-dim)', color: 'var(--muted)', padding: '6px 14px', fontSize: 11, cursor: 'pointer', borderRadius: 0 }}>{q}</button>))}</div>
                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                            {aiResponse && (<div className="card-gold" style={{ padding: '32px' }}><div className="gold-line-top" /><div className="cinzel" style={{ fontSize: 10, letterSpacing: '.25em', color: 'var(--gold)', marginBottom: 16 }}>AI Advisor Response</div><div style={{ fontSize: 14, color: 'var(--text-2)', lineHeight: 1.9, whiteSpace: 'pre-wrap' }}>{aiResponse}</div></div>)}
                                                                                                                                                                                                                                                                                                                                      </div>)}
                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                {!loading && tab === 'notifications' && (<div>
                                                                                                                                                                                                                                                                                                                                                            <div className="eyebrow" style={{ marginBottom: 24 }}>Activity Feed</div>
                                                                                                                                                                                                                                                                                                                                                                        {notifLog.length === 0 ? <Empty main="No activity yet" sub="Recent bookings, reviews, and automations will appear here." /> : notifLog.map((n, i) => (<div key={i} className="card" style={{ padding: '18px 24px', marginBottom: 2, display: 'flex', alignItems: 'center', gap: 16 }}><span style={{ fontSize: 20, flexShrink: 0 }}>{n.type === 'booking' ? '\uD83D\uDCC5' : n.type === 'review' ? '\u2B50' : '\u26A1'}</span><div style={{ flex: 1 }}><div style={{ fontSize: 13, color: 'var(--text)' }}>{n.text}</div></div><div style={{ fontSize: 11, color: 'var(--muted)', flexShrink: 0 }}>{timeAgo(n.time)}</div></div>))}
                                                                                                                                                                                                                                                                                                                                                                                  </div>)}
                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                            {!loading && tab === 'referrals' && (<div>
                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ display: 'flex', gap: 2, marginBottom: 32 }}><Stat label="Total Referrals" value={clients.filter(c => c.referred_by).length} sub="clients referred" /><Stat label="Referral Revenue" value={`$${clients.filter(c => c.referred_by).reduce((s, c) => s + (c.total_spent || 0), 0)}`} sub="from referred clients" /></div>
                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="card-gold" style={{ padding: '24px', marginBottom: 24, position: 'relative' }}><div className="gold-line-top" /><div className="cinzel" style={{ fontSize: 10, letterSpacing: '.2em', color: 'var(--gold)', marginBottom: 12 }}>Your Referral Link</div><div style={{ background: 'var(--dark-3)', border: '1px solid var(--border-dim)', padding: '12px 16px', fontSize: 13, color: 'var(--text)', wordBreak: 'break-all' }}>servicemind.vercel.app/book/{salon.slug}?ref=CLIENTPHONE</div><div style={{ fontSize: 11, color: 'var(--muted)', marginTop: 8 }}>Share this with clients. Replace CLIENTPHONE with their number to track referrals.</div></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                {clients.filter(c => c.referred_by).length === 0 ? <Empty main="No referrals yet" sub="When clients book through a referral link, they'll appear here." /> : <div>{clients.filter(c => c.referred_by).map(c => (<div key={c.id} className="card" style={{ padding: '18px 24px', marginBottom: 2, display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}><div><div style={{ fontSize: 13, color: 'var(--text)', marginBottom: 2 }}>{c.name}</div><div style={{ fontSize: 11, color: 'var(--muted)' }}>Referred by: {c.referred_by}</div></div><div style={{ textAlign: 'right' }}><div style={{ fontSize: 13, color: 'var(--gold)' }}>${c.total_spent}</div><div style={{ fontSize: 11, color: 'var(--muted)' }}>{c.total_visits} visits</div></div></div>))}</div>}
                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>)}
                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                    {!loading && tab === 'settings' && (<div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="card-gold" style={{ padding: '36px', marginBottom: 20, position: 'relative' }}><div className="gold-line-top" /><div className="eyebrow" style={{ marginBottom: 20 }}>Shop Profile</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {[['Shop Name', 'shop_name', 'text'], ['Owner Name', 'owner_name', 'text'], ['Phone', 'phone', 'tel'], ['Email', 'email', 'email'], ['City', 'city', 'text'], ['State', 'state', 'text'], ['Business Type', 'salon_type', 'text'], ['Passcode', 'passcode', 'text']].map(([label, key, type]) => (<div key={key}><label style={{ fontSize: 10, letterSpacing: '.2em', textTransform: 'uppercase', color: 'var(--muted)', display: 'block', marginBottom: 6 }}>{label}</label><input className="input" type={type} value={settingsForm[key] || ''} onChange={e => setSettingsForm(p => ({ ...p, [key]: e.target.value }))} /></div>))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button onClick={saveSettings} className="btn-gold" style={{ padding: '15px 36px', marginTop: 24 }}>Save Profile</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="card" style={{ padding: '28px' }}><div className="cinzel" style={{ fontSize: 10, letterSpacing: '.2em', color: 'var(--gold)', marginBottom: 16 }}>What Fires Automatically</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {[['New booking', 'You get a text when someone books'], ['24hr reminder', 'Client gets a reminder the day before'], ['1hr reminder', 'Client gets a reminder 1 hour before'], ['After visit', 'Review request after each appointment'], ['45 days quiet', 'Win-back text for inactive clients'], ['Birthday', 'Special offer on client birthday']].map(([t, d], i) => (<div key={i} style={{ display: 'flex', gap: 16, marginBottom: 16 }}><span style={{ color: 'var(--gold)', fontSize: 10, marginTop: 4 }}>&diams;</span><div><div style={{ fontSize: 13, color: 'var(--text)', marginBottom: 2 }}>{t}</div><div style={{ fontSize: 12, color: 'var(--muted)' }}>{d}</div></div></div>))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
